PrisonEscape : main.cpp HeaderAll.hpp Items.hpp Items.cpp Map.hpp Map.cpp Spaces.hpp Spaces.cpp YourCell.cpp YourCell.hpp CellHallway.hpp CellHallway.cpp OtherCell.hpp OtherCell.cpp Hallway1.hpp Hallway1.cpp Hallway2.hpp Hallway2.cpp GuardBreakRoom.hpp GuardBreakRoom.cpp UtilityCloset.hpp UtilityCloset.cpp Laundry.hpp Laundry.cpp Kitchen.hpp Kitchen.cpp Armory.cpp Armory.hpp Exit.cpp Exit.hpp
	g++ -std=c++0x main.cpp Items.cpp Map.cpp Spaces.cpp YourCell.cpp CellHallway.cpp OtherCell.cpp Hallway1.cpp Hallway2.cpp GuardBreakRoom.cpp UtilityCloset.cpp Laundry.cpp Kitchen.cpp Armory.cpp Exit.cpp -o PrisonEscape


clean:
	$(RM) PrisonEscape 